package com.skilldistillery.recipemeetup.entities;

import java.util.ArrayList;
import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;

// This entity correlates with the Address table in the database
@Entity
public class Address {
	
	// The fields below correlate with fields in the address table in the database
	// Id is a primary key and autogenerated by the database, hence annotated with Id and GeneratedValue
	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	private int id;
	
	private String street;
	private String city;
	private String state;
	
	//Column annotation gives JPA the exact name in the database of the table that whose imput will be matched by this field.
	@Column(name="postal_code")
	private String postalCode;

	public int getId() {
		return id;
	}
	
	
	/*The javax.persistence.CascadeType enumerated type defines the cascade operations that are applied in the cascade element of the relationship annotations.
	 * If the parent entity is persisted into the persistence context, the related entity will also be persisted. 
	 * If the parent entity is removed from the current persistence context, the related entity will also be removed. 
	 */
	
	
	@OneToMany(cascade = {CascadeType.PERSIST, CascadeType.REMOVE}, mappedBy="address")
	private List<User> users;
	
	//One to many means that there can be one address to many meetups
	//meetupAddress inside mappedBy correlates to the name of the variable that has a ManyToOne relationship with this class. 
	@OneToMany(cascade = {CascadeType.PERSIST, CascadeType.REMOVE}, mappedBy="meetupAddress")
	private List <Meetup> meetups;
	
	
	
	//This method will add an instance of a User class to the list addresses
	 public void addUser(User user) {
	        if(users==null) {
	            users = new ArrayList<>();
	        }
	        
	        if(!users.contains(user)) {
	            users.add(user);
	            if(user.getAddress() != null) {
	                user.getAddress().getUsers().remove(user);
	            }
	        }
	        
	        user.setAddress(this);
	    }
	    
	 //This method will remove a user from the list of users called users
	    public void removeUser(User user) {
	        user.setAddress(null);
	        if(users!=null) {
	            users.remove(user);
	        }
	    }
	    
	    //Below this point you will find add and remove methods for other fields; getters and setters; and toString;
	    
	    public void addMeetups(Meetup meetup) {
	    	if(meetups==null) {
	    		meetups = new ArrayList<>();
	    	}
	    	
	    	if(!meetups.contains(meetup)) {
	    		meetups.add(meetup);
	    		if(meetup.getMeetupAddress() != null) {
	    			meetup.getMeetupAddress().getMeetups().remove(meetup);
	    		}
	    	}
	    	
	    	meetup.setMeetupAddress(this);
	    }
	    
	    public void removeMeetups(Meetup meetup) {
	    	meetup.setMeetupAddress(null);
	    	if(meetups!=null) {
	    		meetups.remove(meetup);
	    	}
	    }

	public String getStreet() {
		return street;
	}

	public void setStreet(String street) {
		this.street = street;
	}

	public String getCity() {
		return city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getState() {
		return state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public List<User> getUsers() {
		return users;
	}

	public void setUsers(List<User> users) {
		this.users = users;
	}

	public String getPostalCode() {
		return postalCode;
	}

	public void setPostalCode(String postalCode) {
		this.postalCode = postalCode;
	}

	public Address() {}
	
	public Address(int id, String street, String city, String state, String postalCode) {
		super();
		this.id = id;
		this.street = street;
		this.city = city;
		this.state = state;
		this.postalCode = postalCode;
	}

	//ToString
	@Override
	public String toString() {
		return "Address [id=" + id + ", street=" + street + ", city=" + city + ", state=" + state + ", postalCode="
				+ postalCode + "]";
	}

	//Since id is unique (correlates to theprimary key in the database), hashcode and equals methods will only take id as a parameter;
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + id;
		return result;
	}

	

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Address other = (Address) obj;
		if (id != other.id)
			return false;
		return true;
	}


	public void setId(int id) {
		this.id = id;
	}

	public List<Meetup> getMeetups() {
		return meetups;
	}

	public void setMeetups(List<Meetup> meetups) {
		this.meetups = meetups;
	}

}
