package com.skilldistillery.recipemeetup.entities;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.CreationTimestamp;

//This entity informs JPA that the class represents a table from the database (Instances will hold values from the table rows, and can populate the DB).
@Entity
public class Meetup {
	
	// the fields below correlate with fields in the address table in the database
	//Id is a primary key and autogenerated by the database, hence annotated with Id and GeneratedValue
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private int id;
	
	
	private String title;

	
	// Column annotation informs JPA which column the field is mapped to (has to have the same name as in the DB).
	// The field is a timestamp which will have the value of the timestamp at the time of creation. 
	// Hence Temporal and CreationTimestamp annotations are used.
	@Column(name = "date_created")
	@Temporal(TemporalType.TIMESTAMP)
	@CreationTimestamp
	private Date createDate;
	
	//Column annotation gives JPA the exact name in the database of the table that whose imput will be matched by this field.
	@Column(name="img_url")
	private String imgURL;
	
	private String description;
	
	@Column(name="maximum_attendance")
	private int maxAttendance;
	
	//Fields that have exactly the same name as the correlating table in the DB will be mapped even without the @Column annotation.
	private boolean active;
	
	@Column(name="start_time")
	@Temporal(TemporalType.TIMESTAMP)
	private Date startTime;
	
	@Column(name="end_time")
	@Temporal(TemporalType.TIMESTAMP)
	private Date endTime;
	
	//The JoinColumn tells JPA which column from the DB is the foreign key that will match this class to the other class (In this cas Meetup to User).
	@ManyToOne
	@JoinColumn(name="author_id")
	private User meetupOwner;
	
	/* A join table annotation is used for  mapping  many-to-many association. 
	 * The join table is a simple merge table that has a ManyToOne connection to both tables, allowing for a ManyToMany relationship to be mapped through this table.
	 * joinColumn corresponds to the foreign key column in the DB to this class (user_meetup to Meetup)
	 * inverseJoinColumns corresponds to the  foreign key column in the DB to the other class (user_meetup to User)
	 */
	@ManyToMany
	@JoinTable(name="user_meetup",
	joinColumns=@JoinColumn(name="meetup_id"),
	inverseJoinColumns=@JoinColumn(name="user_id"))
	private List<User> attendees;
	
	
	
	@OneToMany(cascade = {CascadeType.PERSIST, CascadeType.REMOVE}, mappedBy="meetupCommentedOn")
	private List<MeetupComment> meetupComments;

	@ManyToOne
	@JoinColumn(name="address_id")
	private Address meetupAddress;
	
	
	//Below this point you will find simple add and remove methods for other fields; getters and setters; and toString;
	// More info about these methods inside Address Entity around line 44.
	 public void addAttendee(User attendee) {
	        if(attendees== null) {
	            attendees = new ArrayList<>();
	        }
	        
	        if(!attendees.contains(attendee)) {
	            attendees.add(attendee);
	            attendee.addMeetupAttended(this);
	        }
	        
	    }
	    
	    public void removeAttendee(User attendee ) {
	        if(attendees != null && attendees.contains(attendee)) {
	        attendees.remove(attendee);
	        attendee.removeMeetupAttended(this);
	        }
	    }
	    
	    
	    public void addMeetupComment(MeetupComment meetupComment) {
	    	if(meetupComments==null) {
	    		meetupComments = new ArrayList<>();
	    	}
	    	
	    	if(!meetupComments.contains(meetupComment)) {
	    		meetupComments.add(meetupComment);
	    		if(meetupComment.getMeetupCommentedOn() != null) {
	    			meetupComment.getMeetupCommentedOn().getMeetupComments().remove(meetupComment);
	    		}
	    	}
	    	
	    	meetupComment.setMeetupCommentedOn(this);
	    }
	    
	    public void removeMeetupComment(MeetupComment meetupComment) {
	    	meetupComment.setMeetupCommentedOn(null);
	    	if(meetupComments!=null) {
	    		meetupComments.remove(meetupComment);
	    	}
	    }
	
	public Meetup() {
		super();
	}

	
	public Meetup(int id, String title, Date createDate, String imgURL, String description, int maxAttendance,
			boolean active, Date startTime, Date endTime, User meetupOwner, List<User> attendees,
			List<MeetupComment> meetupComments, Address meetupAddress) {
		super();
		this.id = id;
		this.title = title;
		this.createDate = createDate;
		this.imgURL = imgURL;
		this.description = description;
		this.maxAttendance = maxAttendance;
		this.active = active;
		this.startTime = startTime;
		this.endTime = endTime;
		this.meetupOwner = meetupOwner;
		this.attendees = attendees;
		this.meetupComments = meetupComments;
		this.meetupAddress = meetupAddress;
	}

	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getTitle() {
		return title;
	}

	public void setName(String name) {
		this.title = title;
	}


	public Date getCreateDate() {
		return createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public String getImgURL() {
		return imgURL;
	}

	public void setImgURL(String imgURL) {
		this.imgURL = imgURL;
	}
	

	public Address getMeetupAddress() {
		return meetupAddress;
	}

	public void setMeetupAddress(Address meetupAddress) {
		this.meetupAddress = meetupAddress;
	}

	public int getMaxAttendance() {
		return maxAttendance;
	}

	public void setMaxAttendance(int maxAttendance) {
		this.maxAttendance = maxAttendance;
	}

	public Boolean getActive() {
		return active;
	}

	public void setActive(boolean active) {
		this.active = active;
	}

	public Date getStartTime() {
		return startTime;
	}

	public void setStartTime(Date startTime) {
		this.startTime = startTime;
	}

	public Date getEndTime() {
		return endTime;
	}

	public void setEndTime(Date endTime) {
		this.endTime = endTime;
	}

	
	
	public List<MeetupComment> getMeetupComments() {
		return meetupComments;
	}

	public void setMeetupComments(List<MeetupComment> meetupComments) {
		this.meetupComments = meetupComments;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + id;
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Meetup other = (Meetup) obj;
		if (id != other.id)
			return false;
		return true;
	}

	@Override
	public String toString() {
		return "Meetup Title: " + title + "\nPosted: " + createDate
				+ "\nDescription: " + description + "\nMaxAttendance: " + maxAttendance + "\nStartTime: " + startTime + "\nEndTime: " + endTime;
	}

	public User getMeetupOwner() {
		return meetupOwner;
	}

	public void setMeetupOwner(User meetupOwner) {
		this.meetupOwner = meetupOwner;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public List<User> getAttendees() {
		return attendees;
	}

	public void setAttendees(List<User> attendees) {
		this.attendees = attendees;
	}
}
