package com.skilldistillery.recipemeetup.entities;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.CreationTimestamp;

//This entity informs JPA that the class represents a table from the database (Instances will hold values from the table rows, and can populate the DB).
@Entity
@Table(name="recipe_comment")
public class RecipeComment {
	
	// The fields below correlate with fields in the address table in the database
	// Id is a primary key and autogenerated by the database, hence annotated with Id and GeneratedValue
	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	private int id;
	
	private String comment;
	
	// Timestamps are annotated with @Temporal
	@Temporal(TemporalType.TIMESTAMP)
	@CreationTimestamp
	private Date timeStamp;
	
	private boolean active;
	
	/* A join table annotation is used for  mapping  many-to-many association. 
	 * The join table is a simple merge table that has a ManyToOne connection to both tables, allowing for a ManyToMany relationship to be mapped through this table.
	 * joinColumn corresponds to the foreign key column in the DB to this class (user_meetup to Meetup)
	 * inverseJoinColumns corresponds to the  foreign key column in the DB to the other class (user_meetup to User)
	 */
	@ManyToMany
	@JoinTable(name="recipe_comment_like",
	joinColumns=@JoinColumn(name="recipe_comment_id"),
	inverseJoinColumns=@JoinColumn(name="user_id"))
	private List<User> recipeCommentLikers;
	
	@ManyToOne
	@JoinColumn(name="user_id")
	private User recipeCommentOwner;
	
	
	@ManyToOne
	@JoinColumn(name="recipe_id")
	private Recipe recipeCommentedOn;
	
	
	public void addRecipeCommentLiker(User commentLiker) {
        if(recipeCommentLikers== null) {
            recipeCommentLikers = new ArrayList<>();
        }
        
        if(!recipeCommentLikers.contains(commentLiker)) {
            recipeCommentLikers.add(commentLiker);
            commentLiker.addRecipeCommentLike(this);
        }
        
    }
    
    public void removeRecipeCommentLiker(User commentLiker) {
        if(recipeCommentLikers != null && recipeCommentLikers.contains(commentLiker)) {
        recipeCommentLikers.remove(commentLiker);
        commentLiker.removeRecipeCommentLike(this);
        }
    }
    
	
    
	//Below this point you will find simple add and remove methods for other fields; getters and setters; and toString;
	// More info about these methods inside Address Entity around line 44.
	public int getId() {
		return id;
	}


	public String getComment() {
		return comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	public Date getTimeStamp() {
		return timeStamp;
	}

	public void setTimeStamp(Date timeStamp) {
		this.timeStamp = timeStamp;
	}

	public Boolean getActive() {
		return active;
	}

	public void setActive(Boolean active) {
		this.active = active;
	}

	@Override
	public String toString() {
		return "recipeComment [id=" + id + ", comment=" + comment
				+ ", timeStamp=" + timeStamp + ", active=" + active + "]";
	}
	
	public RecipeComment() {}

	public RecipeComment(int id, int userId, int recipeId, String comment, Date timeStamp, Boolean active) {
		super();
		this.id = id;
		this.comment = comment;
		this.timeStamp = timeStamp;
		this.active = active;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + id;
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		RecipeComment other = (RecipeComment) obj;
		if (id != other.id)
			return false;
		return true;
	}

	public User getRecipeCommentOwner() {
		return recipeCommentOwner;
	}

	public void setRecipeCommentOwner(User recipeCommentOwner) {
		this.recipeCommentOwner = recipeCommentOwner;
	}

	public List<User> getUserRecipeCommentLikes() {
		return recipeCommentLikers;
	}

	public void setUserRecipeCommentLikes(List<User> userRecipeCommentLikes) {
		this.recipeCommentLikers = userRecipeCommentLikes;
	}

	public Recipe getRecipeCommentedOn() {
		return recipeCommentedOn;
	}

	public void setRecipeCommentedOn(Recipe recipeCommentedOn) {
		this.recipeCommentedOn = recipeCommentedOn;
	}

}
