package com.skilldistillery.recipemeetup.data;

import java.util.List;

import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.transaction.Transactional;

import org.springframework.stereotype.Repository;

import com.skilldistillery.recipemeetup.entities.Meetup;
import com.skilldistillery.recipemeetup.entities.MeetupComment;
import com.skilldistillery.recipemeetup.entities.MeetupComment;
import com.skilldistillery.recipemeetup.entities.User;

@Transactional
@Repository
public class MeetupCommentDAOImpl implements MeetupCommentDAO {
	
	// PersistenceContext - All transactions are automatically started and committed, EntityManagerFactory is not required.
	@PersistenceContext
	private EntityManager em;

	// The method below will persist a Meetup comement to the database. 
	@Override
	public MeetupComment postMeetupComment(Meetup meetup, MeetupComment comment, User author) {
		// Author has a list of Meetup Comments, so we add this comment to the list
		author.addMeetupCommentPosted(comment);
		
		// We set the owner of the meetup comment to the user who posted the comment
		comment.setMeetupCommentOwner(author);
		
		// Add the comment to the meetup on which it was posted
		meetup.addMeetupComment(comment);
		
		// A comment has Meetup which the comment was posted to. We set it below.
		comment.setMeetupCommentedOn(meetup);
		
		//persist the comment
		em.persist(comment);
		
		// Flush will fill in the default and autogenerated values from the database to the java instance.
		em.flush();
		
		return comment;
	}

	// The method below returns a list of all MeetupComments for a specific meetup
	@Override
	public List<MeetupComment> showAllMeetupComments(int id) {
		
		// The query will return all comments from the db where the meetup ID is the int id provided as the parameter
		String query = "SELECT comments FROM MeetupComment comments WHERE comments.meetupCommentedOn.id = :id";
		List<MeetupComment> allComments = em.createQuery(query, MeetupComment.class)
				.setParameter("id", id)
				.getResultList();
		return allComments;
	}

	// the method below will persist changes made to a comment in the database. Not yet implemented in the Front-End.
	@Override
	public MeetupComment editMeetupComment(MeetupComment updateComment, User author) {
		//Retrieve a comment from the db.
		MeetupComment editComment = em.find(MeetupComment.class, updateComment);
		
		// Set changes made
		updateComment.setMeetupCommentOwner(author);
		editComment.setTextContent(updateComment.getTextContent());
		
		// return the comment to the controller (or whichever class the method was called from).
		return editComment;
	}

	// removes a meetup comment from the database. This method is not used in the app. Instead the user can setActiveToFalse (see method below).
	@Override
	public boolean deleteMeetupComment(MeetupComment comment, User author) {
		int id = comment.getId();
		comment.setMeetupCommentOwner(author);
		author.removeMeetupCommentPosted(comment);
		boolean isCommentDeleted = false;
		if(comment != null) {
			em.remove(comment);
			if(em.find(MeetupComment.class, id) == null) {
				isCommentDeleted = true;
			}
		}
		return isCommentDeleted;
	}

	// removes a meetup comment from the database. This method is not used in the app. Instead the user can setActiveToFalse (see method below).
	@Override
	public boolean deleteMeetupCommentById(int id) {
		MeetupComment deleteComment = em.find(MeetupComment.class, id);
		boolean isCommentDeleted = false;
		if(deleteComment != null) {
			em.remove(deleteComment);
			if(em.find(MeetupComment.class, id) == null) {
				isCommentDeleted = true;
			}
		}
		return isCommentDeleted;
	}

	// Sets a boolean Active to false. In the front end, comments where Active has a false value will not be displayed.
	@Override
	public MeetupComment setActiveToFalse(MeetupComment meetupComment) {
		meetupComment = em.find(MeetupComment.class, meetupComment.getId());
		meetupComment.setActive(false);
		return meetupComment;
	}

}
