package com.skilldistillery.recipemeetup.data;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.transaction.Transactional;

import org.springframework.stereotype.Repository;

import com.skilldistillery.recipemeetup.entities.Recipe;
import com.skilldistillery.recipemeetup.entities.RecipeComment;
import com.skilldistillery.recipemeetup.entities.User;

//This class manages database interactions where RecipeComment entity is involved.
@Transactional
@Repository
public class RecipeCommentDAOImpl implements RecipeCommentDAO {
	
	// PersistenceContext - All transactions are automatically started and committed, EntityManagerFactory is not required.
	@PersistenceContext
	private EntityManager em;

	// The method below will persist a Recipe comement to the database. 
	@Override
	public RecipeComment postRecipeComment(Recipe recipe, RecipeComment comment, User author) {
		// Author has a list of Recipe Comments, so we add this comment to the list
		author.addRecipeComment(comment);
		
		// We set the owner of the recipe comment to the user who posted the comment
		comment.setRecipeCommentOwner(author);
		
		// Add the comment to the recipe on which it was posted
		recipe.addRecipeComment(comment);
		
		// Set in Comment - Recipe which the comment was posted to 
		comment.setRecipeCommentedOn(recipe);
		
		//persist the comment
		em.persist(comment);
		
		// Flush will fill in the default and autogenerated values from the database to the java instance.
		em.flush();
		return comment;
	}

	// The method below returns a list of AllRecipeComments for a specific recipe
	@Override
	public List<RecipeComment> showAllRecipeComments(int id) {
		
		// The query will return all comments from the db where the recipe ID is the int id provided as the parameter
		String query = "SELECT comments FROM RecipeComment comments WHERE comments.recipeCommentedOn.id = :id";
		List<RecipeComment> allComments = em.createQuery(query, RecipeComment.class)
				.setParameter("id", id)
				.getResultList();
		return allComments;
	}
	
	// the method below will persist changes made to a comment in the database. Not yet implemented in the Front-End.
	@Override
	public RecipeComment editRecipeComment(RecipeComment updateComment, User author) {
		//Retrieve a comment from the db.
		RecipeComment editComment = em.find(RecipeComment.class, updateComment.getId());
		
		// Set changes made
		updateComment.setRecipeCommentOwner(author);
		editComment.setComment(updateComment.getComment());
		
		// return the comment to the controller (or whichever class the method was called from).
		return editComment;
	}

	// removes a recipe comment from the database. This method is not used in the app. Instead the user can setActiveToFalse (see method below).
	@Override
	public boolean deleteRecipeComment(RecipeComment comment, User author) {
		int id = comment.getId();
		comment.setRecipeCommentOwner(author);
		author.removeRecipeComment(comment);
		boolean isCommentDeleted = false;
		if(comment != null) {
			em.remove(comment);
			if(em.find(RecipeComment.class, id) == null) {
				isCommentDeleted = true;
			}
		}
		return isCommentDeleted;
	}

	// removes a recipe comment from the database. This method is not used in the app. Instead the user can setActiveToFalse (see method below).
	@Override
	public boolean deleteRecipeCommentById(int id) {
		RecipeComment deleteComment = em.find(RecipeComment.class, id);
		boolean isCommentDeleted = false;
		if(deleteComment != null) {
			em.remove(deleteComment);
			if(em.find(RecipeComment.class, id) == null) {
				isCommentDeleted = true;
			}
		}
		
		return isCommentDeleted;
	}
	
	// Sets a boolean Active to false. In the front end, comments where Active has a false value will not be displayed.
	@Override
	public RecipeComment setActiveToFalse(RecipeComment recipeComment) {
		recipeComment = em.find(RecipeComment.class, recipeComment.getId());
		recipeComment.setActive(false);
		return recipeComment;
	}

}
